CREATE DATABASE IF NOT EXISTS formula_1;

USE formula_1;

CREATE TABLE IF NOT EXISTS paises(
    id_pais INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    dominio CHAR(2) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS pilotos(
    id_piloto INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    nacionalidad INTEGER UNSIGNED NOT NULL,
    numero_campeonatos INTEGER UNSIGNED NOT NULL,
    FOREIGN KEY(nacionalidad)
        REFERENCES paises(id_pais)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS circuitos(
    id_circuitos INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    pais_id INTEGER UNSIGNED NOT NULL,
    longitud INTEGER UNSIGNED NOT NULL,
    clima VARCHAR(20) NOT NULL,
    FOREIGN KEY(pais_id)
    	REFERENCES paises(id_pais)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scuderias(
    id_scuderia INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    piloto_id INTEGER UNSIGNED NOT NULL,
    fundador VARCHAR(50) NOT NULL,
    fecha_fundacion DATETIME NOT NULL,
    victorias INTEGER UNSIGNED NOT NULL,
    presidente VARCHAR(50) NOT NULL,
    FOREIGN KEY(piloto_id)
    	REFERENCES pilotos(id_piloto)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tablas_posiciones(
    posiciones_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    scuderia_id INTEGER UNSIGNED NOT NULL,
    circuito INTEGER UNSIGNED NOT NULL,
    puntos INTEGER NOT NULL,
    FOREIGN KEY(scuderia_id)
    	REFERENCES scuderias(id_scuderia)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE,
	FOREIGN KEY(circuito)
    	REFERENCES circuitos(id_circuitos)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


